project:
  type: book
  output-dir: docs

book:
  title: "STAT 340: Data Science II"
  author: "Brian Powers"
  date: "5/7/2025"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Sampling"
    - rv.qmd
    - cov.qmd
    - part: "Testing"
    - part: "Estimation"
    - part: "Prediction"
    - part: "Practice"
    - rv_practice.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

