project:
  type: book
  output-dir: docs

book:
  title: "STAT 340: Data Science II"
  author: "Brian Powers"
  date: "5/7/2025"
  reader-mode: true
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Sampling"
      chapters:
      - rv.qmd
      - R01_RandomVariables.Rmd
      - rv_practice.qmd
      - text: "---"
      - cov.qmd
      - R02_IndepCondBayes.Rmd
      - cov_practice.qmd
      - text: "---"
      - mc.qmd
      - R03_MonteCarloExamples.Rmd
      - mc_practice.qmd
      - R_MonteCarlo_Battleship.Rmd
    - part: "Testing"
    - part: "Estimation"
    - part: "Prediction"
  appendices:
    - RV_summary.qmd
bibliography: references.bib

format:
  html:
    theme:
      cosmo
  pdf:
    documentclass: scrreprt

editor: source

