project:
  type: book
  output-dir: docs

book:
  title: "STAT 340: Data Science II"
  author: "Brian Powers"
  date: "5/7/2025"
  reader-mode: true
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Sampling"
      chapters:
      - rv.qmd
      - R01_RandomVariables.Rmd
      - rv_practice.qmd
      - text: "---"
      - cov.qmd
      - R02_IndepCondBayes.Rmd
      - cov_practice.qmd
      - text: "---"
      - mc.qmd
      - R03_MonteCarloExamples.Rmd
      - mc_practice.qmd
      - R_MonteCarlo_Battleship.Rmd
    - part: "Testing"
      chapters:
      - testing1.qmd
      - R04_Monte_Carlo_Testing.Rmd
      - testing1_practice.qmd
      - text: "---"
      - R05_testing_Additional_Examples.Rmd
      - testing2_practice.qmd
    - part: "Estimation"
      chapters:
      - estimation1_practice.qmd
      - R06_More_Estimation_Examples.Rmd
      - text: "---"
      - estimation2_practice.qmd
      - R07_More_Estimation_and_CI_Examples.Rmd
    - part: "Prediction"
      chapters:
      - slr_practice.qmd
      - R08_prediction_examples.Rmd
      - text: "---"
      - mlr_practice.qmd
      - text: "---"
      - logistic_practice.qmd
      - text: "---"
      - cv_practice.qmd
      - text: "---"
      - bootstrap_practice.qmd
  appendices:
    - RV_summary.qmd
bibliography: references.bib

format:
  html:
    theme:
      cosmo
  pdf:
    documentclass: scrreprt

editor: source

