---
title: "Monte Carlo Battleship"
author: "Brian Powers"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This code will demonstrate how you can use Monte Carlo Simulation to create an AI opponent in Battleship.

First a few function that will be used throughout.
```{r}
# constants representing hits and misses.
HIT <- 9; MISS <- -9

placeShip <- function(board, shipIndex){
  isLegal <- FALSE
  giveUp <- 0
  while(!isLegal & giveUp < 100){
    giveUp <- giveUp+1
    orientation = sample(2,1) #upright or across
    if(orientation==2) {board <- t(board)}
    shipLength = shipSizes[shipIndex]
    shipX = sample(1:(dim(board)[1]-shipLength+1),1)
    shipY = sample(1:(dim(board)[2]),1)
    isLegal = prod(board[shipX:(shipX+shipLength-1), shipY] %in% c(0,HIT))
    if(isLegal){
      board[shipX:(shipX+shipLength-1), shipY] <- shipIndex
    }
    if(orientation==2) {board <- t(board)}
  }
  if(isLegal){
    return(board)
  } else{
    return(FALSE)
  }
}

placeAllShips <- function(board){
  for(i in which(shipAlive)){
    board <- placeShip(board,i)
    if(!is.matrix(board)) return(FALSE)
  }
  if(sum(board==HIT)==0){
    return(board)
  } else {
    return(FALSE)
  }
}

buildHeatMap <- function(boardKnowledge, NMC=10000){
  boardMap <- matrix(data=0, nrow=boardDim[1], ncol=boardDim[2])
  for(i in 1:NMC){
    placeAll <- placeAllShips(boardKnowledge) 
    if(is.matrix(placeAll)){
      boardMap <- boardMap + (placeAll %in% (1:length(shipAlive))[shipAlive])
    }
  }
  return(boardMap)
}

guessACoord <- function(boardKnowledge, NMC=10000){
  hmap <- buildHeatMap(boardKnowledge, NMC)
  #remove known hits
  hmap[which(boardKnowledge==HIT)] <- 0
  
  guessIndex <- which(hmap == max(hmap))[1]
  guessX <- guessIndex %% boardDim[1]
  if(guessX == 0) {guessX <- 10}
  guessY <- floor((guessIndex-1) / boardDim[2])+1
  return(list(c(guessX,guessY), hmap))
}

resultOfGuess <- function(guess){
  x <- guess[1]; y<- guess[2]; returnstr <- ""
  if(trueBoard[x,y] == 0){
    boardKnowledge[x,y] <<- MISS
    returnstr <- "Miss"
  } else{
    #Hit
    returnstr <-"Hit!"
    boatIndex <- abs(trueBoard[x,y])
    trueBoard[x,y] <<- trueBoard[x,y] * -1
    boardKnowledge[x,y] <<- HIT
    if(sum(trueBoard == boatIndex)==0){
      #sunk it
      boardKnowledge[which(trueBoard==(-boatIndex))] <<- -boatIndex
      returnstr <- paste(returnstr," Sunk Boat ",boatIndex,".",sep="")
      shipAlive[boatIndex] <<- FALSE
    } 
    if(sum(trueBoard>0)==0){
      #All Boats Sunk
      returnstr <- paste(returnstr, "You Lose")
    }
  }
  return(returnstr)
}

```


Test it out. First the setup.
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=3}
library(fields)
#Define board
boardDim=c(10,10)
#Define ship sizes
shipSizes=c(5,4,3,3,2)
#Initialize ship states
shipAlive = rep(TRUE, length(shipSizes))

#initializeKnowledge
# 0 unknown
# 1,2,3, etc hit boat
boardKnowledge=matrix(data=0, nrow=boardDim[1], ncol=boardDim[2])
trueBoard <- placeAllShips(boardKnowledge)

par(mfrow=c(1,2), mar=c(.5, 3, 4, 0))
image(trueBoard, main="Ship Locations", col=tim.colors(),yaxt="n",xaxt="n"); 
  axis(3, at=seq(0,1, length.out=10), labels=LETTERS[1:10], lwd=0, pos=1, cex.axis=.75)
  axis(2, at=seq(0,1, length.out=10), labels=10:1, lwd=0, pos=0, cex.axis=.75); 
image(boardKnowledge, main="Comp Knowledge", col=tim.colors(),yaxt="n",xaxt="n"); 
  axis(3, at=seq(0,1, length.out=10), labels=LETTERS[1:10], lwd=0, pos=1, cex.axis=.75)
  axis(2, at=seq(0,1, length.out=10), labels=10:1, lwd=0, pos=0, cex.axis=.75)
```


Play the Game!!!
```{r, fig.width=7, fig.height=3}
turn <- 0
while(sum(shipAlive)>0 | turn < 9){
  turn <- turn +1
  guessList <- guessACoord(boardKnowledge,1000)
  guess <- guessList[[1]]
  guessResult <- resultOfGuess(guess)
  print(paste("Turn ",turn,": Computer Guesses ",LETTERS[guess[1]],11-guess[2],": ",guessResult, sep=""))
  
  flush.console()
  par(mfrow=c(1,3), mar=c(.5, 3, 3, 0))
  image(guessList[[2]], main="Heatmap", col=tim.colors(),yaxt="n",xaxt="n"); 
  axis(3, at=seq(0,1, length.out=10), labels=LETTERS[1:10], lwd=0, pos=1)
  axis(2, at=seq(0,1, length.out=10), labels=10:1, lwd=0, pos=0)
  image(trueBoard, main="My Board", col=tim.colors(),yaxt="n",xaxt="n");   
  axis(3, at=seq(0,1, length.out=10), labels=LETTERS[1:10], lwd=0, pos=1)
  axis(2, at=seq(0,1, length.out=10), labels=10:1, lwd=0, pos=0)
  image(boardKnowledge, main="Comp Knowledge", col=tim.colors(),yaxt="n",xaxt="n")
  axis(3, at=seq(0,1, length.out=10), labels=LETTERS[1:10], lwd=0, pos=1)
  axis(2, at=seq(0,1, length.out=10), labels=10:1, lwd=0, pos=0)
}
```

